version: '3.1'

services:
  # main database for application runtime
  main-db:
    image: 'postgres'
    container_name: 'main-database-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "2345:5432"

  # database for testing
  test-db:
    image: 'postgres'
    container_name: 'test-database-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "2346:5432"
